- hosts: all
  vars:
    user_name: pahkat

  tasks:
  - name: Install required system packages
    yum: 
      name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2

  - name: Add docker repository
    become: true
    yum_repository:
      name: docker
      description: Docker Repository
      baseurl: https://download.docker.com/linux/centos/docker-ce.repo

  - name: Install Docker
    yum: 
      name: docker-ce

  - name: Start Docker service
    become: true
    service:
      name: docker
      state: started
      enabled: yes

  - name: Create docker group
    group:
      name: docker
      state: present

  - name: Create {{ user_name }} user
    user:
      name: "{{ user_name }}"
      append: true
      groups: docker
      
  - name: Create Directory
    become: yes
    become_user: "{{ user_name }}"
    file:
      owner: "{{ user_name }}"
      group: "{{ user_name }}"
      state: directory
      path: /home/{{ user_name }}/dist

  - name: Deploy Dist
    become: yes
    become_user: "{{ user_name }}"
    unarchive:
      src: dist.tar.gz
      dest: /home/{{ user_name }}/dist

  - name: Install Dist
    become: yes
    become_user: "{{ user_name }}"
    args:
      executable: /bin/bash
    shell: |
      set -euxo pipefail
      echo $PWD
      cd $HOME/dist
      gunzip -c pahkat-server.tar.gz | docker image load

  - name: Create Caddyfile
    become: yes
    become_user: "{{ user_name }}"
    template:
      src: Caddyfile.j2
      dest: /home/{{ user_name }}/dist/Caddyfile

  - name: Create docker-compose.yml
    become: yes
    become_user: "{{ user_name }}"
    template:
      src: docker-compose.yml.j2
      dest: /home/{{ user_name }}/dist/docker-compose.yml

  - name: Create SystemD service
    become: true
    template:
      src: pahkat-server.service.j2
      dest: /etc/systemd/system/pahkat-server.service

  - name: Restart service
    become: true
    systemd:
      name: divvun-api
      daemon_reload: yes
      state: restarted
      enabled: yes
